{% set name = "rtdip-sdk" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rtdip-sdk-{{ version }}.tar.gz
  sha256: aa4338c72807a63c82265ac2dea9f64b45704b166bf3e6abda3ff02b8f2d47dc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - RTDIP_SDK_NEXT_VER={{ version }}
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
    - pytest-runner
  run:
    - python >={{ python_min }},<3.12
    - databricks-sql-connector ==2.9.3
    - azure-identity ==1.12.0
    - pyodbc ==4.0.39
    - pandas <3.0.0,>=1.5.2
    - jinja2 ==3.1.2
    - importlib-metadata >=1.0.0
    - semver ==3.0.0
    - xlrd ==2.0.1
    - grpcio >=1.48.1
    - grpcio-status >=1.48.1
    - googleapis-common-protos >=1.56.4
    - langchain ==0.0.291
    - openai ==0.27.8

test:
  imports:
    - rtdip_sdk
  commands:
    - pip check
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://www.rtdip.io/
  dev_url: https://github.com/rtdip/core/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: ​'The RTDIP SDK for building ingestion pipelines and querying time series data'
  description: |
    ​​Real Time Data Ingestion Platform (RTDIP) SDK is a python software development kit built to provide users, 
    data scientists and developers with the ability to interact with components of the Real Time Data Ingestion Platform.
  doc_url: https://www.rtdip.io/sdk/overview/

extra:
  recipe-maintainers:
    - GBBBAS
    - cching95
    - rodalynbarce
    - JamesKnBr
